toolinfo[fzf]='*linux*amd64*'
toolinfo[exa]='*linux*x86_64*musl*'
toolinfo[delta]='*x86_64*linux*musl*'
toolinfo[fd]='*x86_64*linux*musl*'
toolinfo[ripgrep]='*x86_64*linux*musl*'
toolinfo[bat]='*x86_64*linux*musl*'
toolinfo[volta]='*linux*openssl-1.1*'
