# System-wide .bashrc file for interactive bash(1) shells.

# To enable the settings / commands in this file for login shells as well,
# this file has to be sourced in /etc/profile.

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, overwrite the one in /etc/profile)
PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '

# Commented out, don't overwrite xterm -T "title" -n "icontitle" by default.
# If this is an xterm set the title to user@host:dir
#case "$TERM" in
#xterm*|rxvt*)
#    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
#    ;;
#*)
#    ;;
#esac

# enable bash completion in interactive shells
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Helper function
uniqappend () {
    varname=$1
    x=$2
    case ":${!varname}:" in
        *":$x:"*) :;; # already there
        *) eval $varname=\"\$$varname:\$x\";;
    esac
    eval $varname=\"\$\{$varname\#:\}\"
}
uniqprepend () {
    varname=$1
    x=$2
    case ":${!varname}:" in
        *":$x:"*) :;; # already there
        *) eval $varname=\"\$x:\$$varname\";;
    esac
    eval $varname=\"\$\{$varname\%:\}\"
}

# Remove duplicate entries
if [ -n "$PATH" ]; then
    old_PATH=$PATH:; PATH=
    while [ -n "$old_PATH" ]; do
        x=${old_PATH%%:*}       # the first remaining entry
        uniqappend PATH $x
        old_PATH=${old_PATH#*:}
    done
    unset old_PATH x
fi
if [ -n "$LD_LIBRARY_PATH" ]; then
    old_PATH=$LD_LIBRARY_PATH:; LD_LIBRARY_PATH=
    while [ -n "$old_PATH" ]; do
        x=${old_PATH%%:*}       # the first remaining entry
        uniqappend LD_LIBRARY_PATH $x
        old_PATH=${old_PATH#*:}
    done
    unset old_PATH x
fi

# Extra Path
if [ -d $HOME/.local/bin ]; then
    uniqprepend PATH $HOME/.local/bin
fi

# Extra installations in tools
export TOOLS_PATH=$HOME/tools

for pkg in $TOOLS_PATH/*; do
    case $pkg in
        *.skip)
            continue;;
        */caffe-recurrent)
            continue;;
    esac
    inc_dir=$pkg/include
    bin_dir=$pkg/bin
    lib_dir=$pkg/lib
    if ! [ -d $lib_dir ]; then
        lib_dir=$pkg/lib64
    fi
    if [ -d $inc_dir ]; then
        uniqprepend INCLUDE $inc_dir
    fi
    if [ -d $bin_dir ]; then
        uniqprepend PATH $bin_dir
    fi
    if [ -d $lib_dir ]; then
        uniqprepend LD_LIBRARY_PATH $lib_dir
        uniqprepend LIB $lib_dir
    fi
done
export PATH
export LD_LIBRARY_PATH
export INCLUDE
export LIB

# Alias
alias ls='ls --color=auto -h -v --indicator-style=classify'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -al'

# Editor
export EDITOR=vim
