@version: 4.11
@include "scl.conf"

options {
    chain_hostnames(off);
    create_dirs(no);
    dns_cache(no);
    flush_lines(0);
    group("log");
    keep_hostname(yes);
    log_fifo_size(10000);
    perm(0640);
    stats(freq(0));
    time_reopen(10);
    use_dns(no);
    use_fqdn(no);
};


# 1. Sources
# Listen for incoming remote UDP logs from the Pi
source s_network {
    default-network-drivers();
};

# Capture syslog-ng's own operational logs (highly recommended for debugging)
source s_internal {
    internal();
};

# 2. Destinations
# Where to write the Pi's remote logs
destination d_remote {
    file("/var/log/remote/${FULLHOST}.log" create-dirs(yes));
};

# Where to write syslog-ng's internal logs
destination d_stdout {
    file("/dev/stdout");
};

# 3. Log Paths (Routing)
# Route the network traffic to the Pi log file
log {
    source(s_network);
    destination(d_remote);
};

# Route the internal engine traffic to stdout which is captured by
# systemd-journald
log {
    source(s_internal);
    destination(d_stdout);
};
