# Basic XDG structure
XDG_CONFIG_HOME=${HOME}/.config
XDG_DATA_HOME=${HOME}/.local/share
XDG_CACHE_HOME=${HOME}/.cache

# Move some dotfiles from home directory

## NodeJS repl history file .node_repl_history
NODE_REPL_HISTORY=${XDG_CACHE_HOME}/node/repl_history

## .bash_history
HISTFILE=${XDG_CACHE_HOME}/bash/history

## .python_history
PYTHONHISTFILE=${XDG_CACHE_HOME}/python/history

## .sqlite_history
SQLITE_HISTORY=${XDG_CACHE_HOME}/sqlite/history

## .wgetrc (which contains settings for hsts-file .wget-hsts)
WGETRC=${XDG_CONFIG_HOME}/wget/wgetrc

## GnuPG
GNUPGHOME=${XDG_DATA_HOME}/gnupg

## Zoom
SSB_HOME=${XDG_DATA_HOME}/zoom

## AWS
AWS_SHARED_CREDENTIALS_FILE=${XDG_CONFIG_HOME}/aws/credentials
AWS_CONFIG_FILE=${XDG_CONFIG_HOME}/aws/config

## Rust
CARGO_HOME=${XDG_DATA_HOME}/cargo
RUSTUP_HOME=${XDG_DATA_HOME}/rustup

## Conan
CONAN_USER_HOME=$XDG_CONFIG_HOME

## Docker
DOCKER_CONFIG=${XDG_CONFIG_HOME}/docker

## NPM
NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc

## Jupyter/IPython
IPYTHONDIR=${XDG_CONFIG_HOME}/ipython
JUPYTER_CONFIG_DIR=${XDG_CONFIG_HOME}/jupyter

## Nuget
NUGET_PACKAGES=${XDG_CACHE_HOME}/NuGetPackages

## KDE4
KDEHOME=${XDG_CONFIG_HOME}/kde4

## gtk 2
GTK2_RC_FILES=${XDG_CONFIG_HOME}/gtk-2.0/gtkrc

## kubectl
KUBECONFIG=${XDG_CONFIG_HOME}/kube/config

## Boto used by gcloud
## https://cloud.google.com/storage/docs/boto-gsutil
BOTO_CONFIG=${XDG_CONFIG_HOME}/gcloud/boto.cfg

## Gmailctl
GMAILCTL_CONFIG_DIR=${XDG_CONFIG_HOME}/gmailctl
