"""
%%asmarkdown magic
show the markdown output generated by a code cell in ipython notebook
"""
from __future__ import absolute_import
import sys
from io import StringIO
from markdown import markdown
from IPython.core.getipython import get_ipython
from IPython.core.magic import (Magics, magics_class, cell_magic)
from IPython.core.display import HTML

@magics_class
class MarkdownMagics(Magics):
    """asmarkdown magic class"""
    @cell_magic
    def asmarkdown(self, line, cell):
        buffer = StringIO()
        stdout = sys.stdout
        sys.stdout = buffer
        try:
            exec(cell, locals(), self.shell.user_ns)
        except:
            sys.stdout = stdout
            raise
        sys.stdout = stdout
        return HTML("<p>{}</p>".format(markdown(buffer.getvalue(),
                                                extensions=['markdown.extensions.extra'])))

get_ipython().register_magics(MarkdownMagics)
