#! /usr/bin/env python3

from urllib.parse import urlparse
from subprocess import check_call, check_output
import logging


def handle_ssh(url):
    url = urlparse(url)

    cmd = []

    if url.scheme == 'ssh':
        cmd += [
            'ssh'
        ]
    else:
        logging.critical(f"Invalid protocol {url.scheme}")
        sys.exit(1)

    if url.username:
        cmd += [
            '-l',
            url.username
        ]

    if url.hostname:
        cmd += [
            url.hostname
        ]
    else:
        logging.error(f"Invalid hostname {url.hostname}")

    if url.port:
        if url.scheme == 'ssh':
            cmd += [
                '-p',
                url.port
            ]

    logging.debug(f"Running command {cmd}")
    check_call(['yakuake-exec'] + [str(elem) for elem in cmd])


if __name__ == '__main__':
    import sys
    import os
    logpath = os.environ.get("YAKUAKE_EXEC_DEBUG", "")
    if logpath:
        logging.basicConfig(filename=logpath, level=logging.DEBUG)
    else:
        logging.disable(logging.DEBUG)
    logging.debug(f"Got sysv argv: {sys.argv}")
    logging.debug(f"My env: {os.environ}")
    for elem in sys.argv[1:]:
        handle_ssh(elem)
