#! /bin/sh

inputmkv=$1
outputgif=${2:-'output.gif'}
width=${3:-640}

palette=$(mktemp --tmpdir palette-XXXXXXXX.png)
ffmpeg -y -i "$inputmkv" -vf fps=10,scale=${width}:-1:flags=lanczos,palettegen "$palette"
ffmpeg -i "$inputmkv" -i "$palette" -filter_complex "fps=10,scale=${width}:-1:flags=lanczos[x];[x][1:v]paletteuse" "$outputgif"
rm "$palette"
