#! /usr/bin/env python

import sys


prices = []
p = 0.0
for s in sys.argv[1:]:
    try:
        p = p + float(s)
    except ValueError:
        # this is seprater
        prices.append(p)
        p = 0.0
total = p
running = sum(prices)
for p in [round(p / running * total, 2) for p in prices]:
    print(p)
